version: "3.8"

services:
  n8n:
    image: n8nio/n8n
    container_name: n8n
    restart: unless-stopped
    ports:
      - "#tentukanport#:5678"
    environment:
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - N8N_HOST=192.168.1.8
      - N8N_PATH=/
      - N8N_EDITOR_BASE_URL=http://192.168.1.8:8888
      - WEBHOOK_URL=http://192.168.1.8:8888
      - N8N_SECURE_COOKIE=false
      - TZ=Asia/Jakarta
      - GENERIC_TIMEZONE=Asia/Jakarta
    volumes:
      - ./n8n_data:/home/node/.n8n
